version: '3.8'
services:
  api-gateway:
    build: ./services/api-gateway
    ports: ['3000:3000']
  modules-service:
    build: ./services/modules-service
    ports: ['4002:4002']
  auth-service:
    build: ./services/auth-service
    ports: ['4000:4000']
  admin:
    build: ./admin
    ports: ['3005:3005']
